enableTransparentWorkspaces: false

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-anyFallBackMockValue}"

npmPublishRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
